import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
  },
  camera: {
    flex: 1,
    backgroundColor: 'green',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    alignItems: 'center',
    position: 'absolute',
    bottom: '13%',
    width: '100%',
  },
  disabledButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    alignItems: 'center',
    position: 'absolute',
    bottom: '13%',
    width: '100%',
    disabled: true,
  },
  buttonContainerUp: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: '30%',
    width: '100%',
  },
  smallButton: {
    borderWidth: 1,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    width: 80,
    height: 80,
    backgroundColor: '#fff',
    borderRadius: 40,
    margin: '3%',
    opacity: 0.6,
    disabled: true,
  },
  activeSmallButton: {
    borderWidth: 1,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    width: 80,
    height: 80,
    backgroundColor: 'black',
    borderRadius: 40,
    margin: '3%',
    opacity: 0.6,
  },
  bigButton: {
    borderWidth: 1,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    width: 100,
    height: 100,
    backgroundColor: '#fff',
    borderRadius: 50,
    margin: '3%',
  },
  backButtonContainer: {
    position: 'absolute',
    top: '8%',
    left: '8%',
    borderWidth: 1,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    width: 50,
    height: 50,
    backgroundColor: 'rgba(255,255,255,0.6)',
    borderRadius: 40,
  },
  searchResultScrollView: {
    flex: 1,
  },
  searchResultItemScrollViewContainer: {
    flex: 1,
    position: 'absolute',
    bottom: '13%',
    height: '15%',
    paddingRight: '5%',
    paddingLeft: '5%',
    width: '100%',
  },
  scannerLoadingContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.7)',
  },
});
